GET http://localhost:8080/api/user/a HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhWZmtYZGZkLXdIM3kyQURMMVV3dyJ9.eyJpc3MiOiJodHRwczovL2Rldi1nNHd3NHd3bi51cy5hdXRoMC5jb20vIiwic3ViIjoiYk1jZjlBaFVrUFVHV2NlQTlRYlprR0gzbHVIRURrek5AY2xpZW50cyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImlhdCI6MTY2OTk4NzU2NSwiZXhwIjoxNjcwMDczOTY1LCJhenAiOiJiTWNmOUFoVWtQVUdXY2VBOVFiWmtHSDNsdUhFRGt6TiIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.HZXoIwQLEOIXJop63z9yMBlQCUCV8oa95Y9Re5BApaivTS8V9Y663LvmiZWp3528LChprR4XKK7cJ3PKKK9eHuMG8qqxpjL0tgKo-Inn-q4RmG3zWhjuGAYU2UTAqNrhXxZKoHuVLF2GciUGZPbgN1MUP5yy1l_B-qofEKhjHA7IrgJiRPSNVhI2lB_MvnM7z0dAsUijxGsUZ569R0Y1k9jN8guhJUZ0__oVOuqfTXclJIEEBymQtGdA7H7wsbF677obwflAxxlU4kj3N0eyYeIItakSBr0b2AWrBMXJNSnk3Pi7zAd5s5XN3JIV978z7EYZNNhTQR0TJOZHl1nydg
